# Generated by Django 2.1.4 on 2019-01-28 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190128_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote',
            field=models.SmallIntegerField(choices=[(1, 'THUMBS UP'), (0, 'THUMBS DOWN')]),
        ),
    ]
