# Generated by Django 2.1.4 on 2019-01-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190128_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote',
            field=models.SmallIntegerField(choices=[(1, 'THUMBS UP'), (-1, 'THUMBS DOWN')]),
        ),
    ]
